# SmartProxy Configuration Example
# Copy this file to config.yaml and update with your settings

# Local proxy server settings
server:
  http_port: 8888     # HTTP/HTTPS proxy port
  
  # HTTPS interception settings
  https_mitm: false    # Enable/disable HTTPS interception (MITM)
  ca_cert: ""          # Path to CA certificate file (leave empty to auto-generate)
  ca_key: ""           # Path to CA private key file (leave empty to auto-generate)
  
  # Performance settings for high concurrency
  max_idle_conns: 10000        # Maximum idle connections
  max_idle_conns_per_host: 100 # Maximum idle connections per host
  idle_conn_timeout: 90         # Idle connection timeout in seconds
  tls_handshake_timeout: 10     # TLS handshake timeout in seconds
  expect_continue_timeout: 1    # Expect continue timeout in seconds
  
  # Buffer settings
  read_buffer_size: 65536       # Read buffer size (64KB)
  write_buffer_size: 65536      # Write buffer size (64KB)

# Upstream proxy settings (REQUIRED - proxy will not start without this)
upstream:
  proxy_url: ""                 # e.g., "http://proxy.com:8080" or "socks5://127.0.0.1:1080"
  username: ""                  # Proxy authentication username
  password: ""                  # Proxy authentication password

# Ad blocking settings
ad_blocking:
  enabled: true
  domains_file: "ad_domains.yaml"

# File extensions to handle directly (bypass proxy)
direct_extensions:
  # Documents
  - .pdf
  - .doc
  - .docx
  
  # Images
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .webp
  - .svg
  - .ico
  
  # Videos
  - .mp4
  - .webm
  - .avi
  - .mov
  
  # Audio
  - .mp3
  - .wav
  - .ogg
  
  # Web assets
  - .css
  - .js
  - .woff
  - .woff2
  
  # Archives
  - .zip
  - .rar
  - .7z

# CDN domains to handle directly for HTTPS
direct_domains:
  # Common CDN patterns
  - cdn.
  - static.
  - assets.
  
  # Major CDN providers
  - cloudflare
  - akamai
  - fastly
  - cloudfront
  
  # Popular services
  - googleapis.com
  - gstatic.com
  - jsdelivr.net
  - unpkg.com

# Logging settings
logging:
  level: info      # debug, info, warn, error
  format: text     # text or json