version: '3.8'

services:
  smartproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: smartproxy:latest
    container_name: smartproxy
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      # Mount config files as read-only
      - ./config.yaml:/app/config.yaml:ro
      - ./ad_domains.yaml:/app/ad_domains.yaml:ro
      # Optional: Mount CA certificates if using HTTPS MITM
      # - ./certs:/app/certs:ro
    environment:
      - SMARTPROXY_CONFIG=/app/config.yaml
      # Optional: Set log level
      # - LOG_LEVEL=debug
    networks:
      - proxy-network
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    # Health check
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

networks:
  proxy-network:
    driver: bridge