# SmartProxy Configuration Example
# Copy this file to config.yaml and update with your settings

# Local proxy server settings
server:
  http_port: 8888     # HTTP/HTTPS proxy port
  
  # HTTPS interception settings
  https_mitm: false    # Enable/disable HTTPS interception (MITM)
  ca_cert: ""          # Path to CA certificate file (leave empty to auto-generate)
  ca_key: ""           # Path to CA private key file (leave empty to auto-generate)
  
  # Performance settings for high concurrency
  max_idle_conns: 10000        # Maximum idle connections
  max_idle_conns_per_host: 100 # Maximum idle connections per host
  idle_conn_timeout: 90         # Idle connection timeout in seconds
  tls_handshake_timeout: 10     # TLS handshake timeout in seconds
  expect_continue_timeout: 1    # Expect continue timeout in seconds
  
  # Buffer settings
  read_buffer_size: 65536       # Read buffer size (64KB)
  write_buffer_size: 65536      # Write buffer size (64KB)

# Smart Proxy Mode - Upstream is configured via authentication
# No need to declare upstream in config file!
# 
# Authentication format:
# Username: schema (http or socks5)
# Password: base64 encoded upstream details
# 
# Examples:
# - Without upstream auth: base64("host:port")
#   Username: http
#   Password: bmEubHVuYXByb3h5LmNvbToxMjIzMw== (na.lunaproxy.com:12233)
#
# - With upstream auth: base64("host:port:username:password")
#   Username: socks5
#   Password: bmEubHVuYXByb3h5LmNvbToxMjIzMzp1c2VyOnBhc3M= (na.lunaproxy.com:12233:user:pass)

# Ad blocking settings
ad_blocking:
  enabled: true
  domains_file: "configs/ad_domains.yaml"

# File extensions to handle directly (bypass proxy)
direct_extensions:
  # Documents
  - .pdf
  - .doc
  - .docx
  
  # Images
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .webp
  - .svg
  - .ico
  
  # Videos
  - .mp4
  - .webm
  - .avi
  - .mov
  
  # Audio
  - .mp3
  - .wav
  - .ogg
  
  # Web assets
  - .css
  - .js
  - .woff
  - .woff2
  
  # Archives
  - .zip
  - .rar
  - .7z

# CDN domains to handle directly for HTTPS
direct_domains:
  # Common CDN patterns
  - cdn.
  - static.
  - assets.
  
  # Major CDN providers
  - cloudflare
  - akamai
  - fastly
  - cloudfront
  
  # Popular services
  - googleapis.com
  - gstatic.com
  - jsdelivr.net
  - unpkg.com

# Logging settings
logging:
  level: debug      # debug, info, warn, error
  format: text     # text or json